CREATE DATABASE IF NOT EXISTS CUSTOMER;
USE CUSTOMER;

CREATE TABLE CUST(
CUSTOMER_ID INT PRIMARY KEY,
CUSTOMER VARCHAR(100) NOT NULL,
MODE VARCHAR(20) NOT NULL,
CITY VARCHAR(50) NOT NULL);

INSERT INTO CUST VALUES(101,"OLIVER","NETBANKING","DELHI"),
(102,"ANKIT","CREDIT CARD","DELHI"),
(103,"SHUBHAM","CREDIT CARD","DELHI"),
(104,"SUMIT","NETBANKING","BIHAR"),
(105,"LIKHITHA","CREDIT CARD","DELHI"),
(106,"AADARSH","DEBIT CARD","BIHAR"),
(107,"OLIVE","DEBIT CARD","UP"),
(108,"ROBIN","NETBANKING","UP"),
(109,"AKANCHA","NETBANKING","DELHI"),
(110,"SINGH ROCKY","CREDIT CARD","BIHAR");

SELECT * FROM CUST;

SELECT MODE, COUNT(MODE) FROM CUST GROUP BY MODE;
SELECT CUSTOMER , MODE FROM CUST ORDER BY MODE ASC;
SELECT CUSTOMER , MODE FROM CUST ORDER BY MODE DESC;