-- DDL(DATA DEFINATION LANGUAGE)
-- CREATE , ALTER , DROP , RENAME , TRUNCATE

-- DQL (DATA QUERY LANGUAGE )
-- SELECT

-- DML (DATA MANIPULATION LANGUAGE) 
-- INSERT , UPDATE , DELETE

-- DCL (DATA CONTROL LANGUAGE)
-- GRANT AND REVOKE PERMISSIONS TO USERS

-- TCL (TRANSACTION CONTROL LANGUAGE)
-- START TRANSACTION , COMMIT , ROLLBACK


CREATE DATABASE IF NOT EXISTS ANKIT;

SHOW DATABASES;

DROP DATABASE IF EXISTS COLLAGE;


     