-- PRIMARY KEY IS COMBINATION OF NOT NULL AND NOT DUPLICATE VALUE(UNIQUE)
-- FOREGIN KEY USED TO CONNECT TWO TABLES FOREGIN KEY CAN BE DUPLICATED AND WE CAN STORE NULL VALUES

CREATE DATABASE IF NOT EXISTS STUDENT;
USE STUDENT ;

CREATE TABLE MARKS(
NAME VARCHAR(100) NOT NULL,
ROLLNO INT NOT NULL UNIQUE,
MARKS FLOAT NOT NULL);

INSERT INTO MARKS VALUES("ANKITR",01,98.5),("SHUBHAM",02,88),("AMAN",03,33),("SUMIT",04,44),
("ROBIN",06,90),("AARYA",07,88),("ANANYA",08,99),("AKANCHA",09,89),("VIJAY",10,78),("MANAV JOSHI",11,90),("ANAND",12,99);
INSERT INTO MARKS VALUES("ANKITR",13,98.5);

SELECT * FROM MARKS WHERE MARKS>80;
SELECT DISTINCT NAME FROM MARKS ;-- IT WILL NOT PRINT DUPLICATE VALUES
SELECT * FROM MARKS; 

CREATE TABLE STUDENT(
NAME VARCHAR(100) NOT NULL,
ROLLNO INT NOT NULL UNIQUE,
MARKS FLOAT NOT NULL);

INSERT INTO STUDENT VALUES("ANKITR",01,98.5),("SHUBHAM",02,88),("AMAN",03,33),("SUMIT",04,44),
("ROBIN",06,90),("AARYA",07,88),("ANANYA",08,99),("AKANCHA",09,89),("VIJAY",10,78),("MANAV JOSHI",11,90),("ANAND",12,99);
INSERT INTO MARKS VALUES("ANKITR",13,98.5);

SELECT NAME FROM STUDENT WHERE MARKS<50;
